name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Release and Update Docs"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and Build
        run: |
          npm ci
          npm run build
          echo "Перевірка, що збудувалося:"
          ls -R  # Ця команда покаже всі папки і файли в логах

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' 

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4