name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate version
        run: |
          echo "VERSION=v1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Create Tag
        run: |
          git tag $VERSION
          git push origin $VERSION

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}